version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 0Y4BfYkzJdac9ZLTl0jh
      MYSQL_DATABASE: yourdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 0Y4BfYkzJdac9ZLTl0jh
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://youruser:yourpassword@db:3306/yourdb
